version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
      nodejs: 12
    commands:
      - npm install -g aws-cdk -y
      - cdk --version
      - pip install -r requirements.txt
  build:
    commands:
      - make build-deploy